### 登录账号
POST {{host}}/account/login
Content-Type: application/json

{
  "principal": "100000",
  "pwd": "123456"
}

### 获取验证码
GET {{host}}/account/register-captcha?email=1878572503@qq.com

### 注册账号
POST {{host}}/account/register
Content-Type: application/json

{
  "email": "twat131@qq.com",
  "captcha": "131",
  "pwd": "123456"
}

### 发送好友请求
POST {{host}}/account/friend-request
Content-Type: application/json
Authorization: Bearer {{TOKEN100001}}

{
  "uid": 100000,
  "msg": "我是 100001"
}

### 获取好友请求列表
GET {{host}}/account/friend-request-list?offset=0
token: {{TOKEN100000}}

### 获取好友列表
GET {{host}}/account/friend-list
Authorization: Bearer {{TOKEN100000}}

### 获取好友ID列表
GET {{host}}/account/friend-uid-list
Authorization: Bearer {{TOKEN100000}}